export const LOAD_LIGHT_HUB_LOCATION = 'app/LOAD_LIGHT_HUB_LOCATION';
export const LOAD_LIGHT_HUB_LOCATION_SUCCESS = 'app/LOAD_LIGHT_HUB_LOCATION_SUCCESS';
export const LOAD_LIGHT_HUB_LOCATION_FAIL = 'app/LOAD_LIGHT_HUB_LOCATION_FAIL';
